[book]
author = "Türkiye Teknolojik Belgeleme Topluluğu"
description = "Türkçe teknolojik belgelerin genişletilmesi amacıyla kurulan topluluk."
language = "tr"
multilingual = false
src = "belgeler"
title = "Türkiye Teknolojik Belgeleme Topluluğu [KATEGORİ] Belgeleri"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/turkiye-tbt/[KATEGORİ]"
edit-url-template = "https://github.com/turkiye-tbt/[KATEGORİ]/edit/main/{path}"

[output.html.print]
enable = false